jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=1236a77e6f9d67
spring.mail.password=1310bad455e1b3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.application.name=tcc
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Erik589@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
